apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-database
  namespace: zebrands
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database-mongo
          image: mongo:3.6
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: svc-database
  namespace: zebrands
  labels:
    app: database
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
