apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-api
  namespace: zebrands
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-rest
          image: mt2h/api-retozebrands:latest
          #image: retozebrands #local image testing
          #imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: "mongodb://svc-database:27017"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-api
  namespace: zebrands
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
